# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: check-termin

on:
  schedule:
      - cron: '*/20 8-18 * * 1-5'
      - cron: '0 19-23 * * 1-5'
      - cron: '*/360 10-23 * * 6-7'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-
    - run: npm ci
    - run: npm start
      env: 
        CHATID: ${{ secrets.CHATID }}
        TOKEN: ${{ secrets.TOKEN }}
